# Generated by Django 5.0.5 on 2024-05-17 09:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default=api.models.get_default_profile_picture,
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
