# Generated by Django 5.0.5 on 2024-05-23 08:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/%Y/%m/%d",
                validators=[api.models.validate_image_size],
            ),
        ),
    ]
