# Generated by Django 5.0.5 on 2024-05-24 06:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_profile_cover_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/%Y/%m/%d",
                validators=[api.models.validate_video],
            ),
        ),
    ]
