version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://0.0.0.0:8000
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://0.0.0.0:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
